baseurl = "https://amartyabb.github.io/OurPromisesIO/"
title = "Our Promises"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true
publishDir = "docs"


[params]
  title = "Our Promises"
  description = '<!--[-->To use technology and media to create simple solutions and promote new, creative ideas in communities everywhere. <!--]--><br />Work to help inspire, inform, and educate young people and those in need. <!--]--><br />THAT’S OUR PROMISE.
                <!--[--></a> <!--]-->'
  logo = "fa-diamond"
  copyright = "Our Promises Inc"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/ourpromises.io/"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "Our Promises"

[languages.de]
languageName = ""
weight = 2
title = "Our Promises"
description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
